const EMAIL_VERIFICATION_TTL_HOURS = 12;
const EMAIL_VERIFICATION_TTL_MS = EMAIL_VERIFICATION_TTL_HOURS * 60 * 60 * 1000;

module.exports = {
  EMAIL_VERIFICATION_TTL_HOURS,
  EMAIL_VERIFICATION_TTL_MS,
};
