const EMAIL_VERIFICATION_TTL_HOURS = 12;
const EMAIL_VERIFICATION_TTL_MS = EMAIL_VERIFICATION_TTL_HOURS * 60 * 60 * 1000;

const ADMIN_APPROVAL_TTL_DAYS = 7;
const ADMIN_APPROVAL_TTL_MS = ADMIN_APPROVAL_TTL_DAYS * 24 * 60 * 60 * 1000;

const PASSWORD_RESET_TTL_MINUTES = 60;
const PASSWORD_RESET_TTL_MS = PASSWORD_RESET_TTL_MINUTES * 60 * 1000;

const MIN_PASSWORD_LENGTH = 8;
const MIN_BCRYPT_SALT_ROUNDS = 10;

module.exports = {
  EMAIL_VERIFICATION_TTL_HOURS,
  EMAIL_VERIFICATION_TTL_MS,
  ADMIN_APPROVAL_TTL_DAYS,
  ADMIN_APPROVAL_TTL_MS,
  PASSWORD_RESET_TTL_MINUTES,
  PASSWORD_RESET_TTL_MS,
  MIN_PASSWORD_LENGTH,
  MIN_BCRYPT_SALT_ROUNDS,
};
