const ERROR_MESSAGES = Object.freeze({
  DUPLICATE_USER: 'משתמש עם מזהה זה כבר קיים במערכת',
  DUPLICATE_EMAIL: 'משתמש עם כתובת דוא"ל זו כבר קיים',
  DUPLICATE_ID_NUMBER: 'משתמש עם תעודת זהות זו כבר קיים',
  INVALID_DATA: 'נתונים לא תקינים',
  INVALID_ROLE: 'תפקיד לא תקין',
  INVALID_CLASS_ID: 'מזהה הכיתה אינו תקין',
  USER_NOT_FOUND: 'המשתמש לא נמצא',
  DELETE_NOT_CONFIRMED: 'יש לאשר את המחיקה באופן מפורש',
  CANNOT_DELETE_SELF: 'לא ניתן למחוק את המשתמש המחובר',
  USER_CREATED: 'המשתמש נוסף בהצלחה',
  USER_UPDATED: 'פרטי המשתמש עודכנו בהצלחה',
  USER_DELETED: 'המשתמש נמחק בהצלחה',
  INVALID_JSON: 'גוף הבקשה אינו JSON תקין',
  NOT_FOUND: 'הנתיב לא נמצא',
  INTERNAL: 'שגיאת שרת פנימית',
  REGISTER_SUCCESS: 'ההרשמה בוצעה בהצלחה',
  EMAIL_SEND_FAILED: 'שליחת המייל נכשלה. נסו שוב מאוחר יותר.',
  INVALID_VERIFICATION_TOKEN: 'קישור האימות אינו תקין',
  EXPIRED_VERIFICATION_TOKEN: 'תוקף קישור האימות פג',
  EMAIL_VERIFIED: 'המייל אומת בהצלחה. החשבון ממתין לאישור ההנהלה.',
  UNAUTHORIZED: 'נדרשת התחברות למערכת',
  FORBIDDEN: 'אין הרשאה לגשת למשאב זה',
  INVALID_CREDENTIALS: 'דואר אלקטרוני או סיסמה שגויים',
  PENDING_EMAIL_VERIFICATION:
    'חשבונך טרם אומת. אנא לחץ על הקישור שנשלח לתיבת הדואר האלקטרוני שלך (הקישור בתוקף ל-12 שעות).',
  PENDING_ADMIN_APPROVAL:
    'חשבונך אומת בהצלחה וממתין לאישור ההנהלה. עדכון יישלח אליך למייל.',
  LOGIN_SUCCESS: 'ההתחברות בוצעה בהצלחה',
  USER_APPROVED: 'התלמיד אושר בהצלחה',
  USER_REJECTED: 'הבקשה נדחתה והמשתמש נמחק',
  PENDING_USER_NOT_FOUND: 'לא נמצא משתמש הממתין לאישור הנהלה',
  FORGOT_PASSWORD_SUCCESS: 'קישור נשלח למייל',
  INVALID_RESET_TOKEN: 'קישור האיפוס אינו תקין',
  EXPIRED_RESET_TOKEN: 'תוקף קישור האיפוס פג',
  RESET_PASSWORD_SUCCESS: 'הסיסמה עודכנה בהצלחה',
  INVALID_CURRENT_PASSWORD: 'סיסמה שגויה',
  PROFILE_UPDATED: 'הפרטים האישיים עודכנו בהצלחה',
  PASSWORD_CHANGED: 'הסיסמה עודכנה בהצלחה',
  INVALID_PROFILE_IMAGE: 'תמונת הפרופיל אינה תקינה',
  INVALID_ATTENDANCE_DATE: 'תאריך הנוכחות אינו תקין',
  INVALID_ACTIVITY_TYPE: 'סוג הפעילות חייב להיות שיעור או תפילה',
  INVALID_ATTENDANCE_STATUS: 'סטטוס הנוכחות אינו תקין',
  ATTENDANCE_RECORDS_REQUIRED: 'יש לשלוח מערך דיווחי נוכחות',
  ATTENDANCE_SAVED: 'הנוכחות נשמרה בהצלחה',
  LESSON_ATTENDANCE_SAVED: 'שמירה בוצעה בהצלחה',
  STUDENT_NOT_IN_RABBI_CLASS: 'ניתן לדווח נוכחות רק לתלמידים בשיעור שלך',
  PHONE_PENALTY_INVALID_TRANSITION: 'לא ניתן לעדכן את סטטוס ההפקדה במצב הנוכחי',
  PHONE_DEPOSIT_CONFIRMED: 'קבלת המכשיר אושרה והספירה לשבוע החלה',
  PHONE_RETURN_CONFIRMED: 'המכשיר הוחזר לתלמיד והמונה אופס',
  INVALID_LEAVE_DATE: 'תאריך החופשה אינו תקין',
  INVALID_LEAVE_RANGE: 'תאריך הסיום חייב להיות באותו יום או אחרי תאריך ההתחלה',
  LEAVE_CREATED: 'החופשה נוספה בהצלחה',
  VACATION_QUOTA_EXCEEDED: 'הבקשה חורגת ממכסת ימי החופשה השנתית',
  VACATION_REQUESTED: 'בקשת החופשה נשלחה בהצלחה',
  VACATION_NOT_FOUND: 'בקשת החופשה לא נמצאה',
  VACATION_NOT_PENDING: 'ניתן לעדכן רק בקשות ממתינות לאישור',
  INVALID_VACATION_STATUS: 'סטטוס החופשה אינו תקין',
  INVALID_VACATION_DAYS: 'מספר ימי החופשה השנתית אינו תקין',
  VACATION_STATUS_UPDATED: 'סטטוס החופשה עודכן בהצלחה',
  VACATION_SETTINGS_UPDATED: 'מכסת ימי החופשה עודכנה בהצלחה',
  MESSAGE_RECIPIENT_REQUIRED: 'יש לבחור תלמיד או כיתה לשליחת ההודעה',
  INVALID_MESSAGE_TYPE: 'סוג ההודעה אינו תקין',
  MESSAGE_BROADCAST_FORBIDDEN: 'אין הרשאה לשלוח הודעה לכלל הישיבה',
  MESSAGE_NOT_IN_RABBI_CLASS: 'ניתן לשלוח הודעה רק לשיעור שלך או לתלמיד שמשתייך אליו',
  MESSAGE_SENT: 'ההודעה נשלחה בהצלחה',
  STUDENT_NOT_IN_SYSTEM: 'תלמיד זה אינו מופיע במערכת',
});

module.exports = {
  ERROR_MESSAGES,
};
