const ERROR_MESSAGES = Object.freeze({
  DUPLICATE_USER: 'משתמש עם מזהה זה כבר קיים במערכת',
  DUPLICATE_EMAIL: 'משתמש עם כתובת דוא"ל זו כבר קיים',
  DUPLICATE_ID_NUMBER: 'משתמש עם תעודת זהות זו כבר קיים',
  INVALID_DATA: 'נתונים לא תקינים',
  INVALID_ROLE: 'תפקיד לא תקין',
  INVALID_CLASS_ID: 'מזהה הכיתה אינו תקין',
  USER_NOT_FOUND: 'המשתמש לא נמצא',
  DELETE_NOT_CONFIRMED: 'יש לאשר את המחיקה באופן מפורש',
  CANNOT_DELETE_SELF: 'לא ניתן למחוק את המשתמש המחובר',
  USER_CREATED: 'המשתמש נוסף בהצלחה',
  USER_UPDATED: 'פרטי המשתמש עודכנו בהצלחה',
  USER_DELETED: 'המשתמש נמחק בהצלחה',
  INVALID_JSON: 'גוף הבקשה אינו JSON תקין',
  NOT_FOUND: 'הנתיב לא נמצא',
  INTERNAL: 'שגיאת שרת פנימית',
  REGISTER_SUCCESS: 'ההרשמה בוצעה בהצלחה',
  EMAIL_SEND_FAILED: 'שליחת המייל נכשלה. נסו שוב מאוחר יותר.',
  INVALID_VERIFICATION_TOKEN: 'קישור האימות אינו תקין',
  EXPIRED_VERIFICATION_TOKEN: 'תוקף קישור האימות פג',
  EMAIL_VERIFIED: 'המייל אומת בהצלחה. החשבון ממתין לאישור ההנהלה.',
  UNAUTHORIZED: 'נדרשת התחברות למערכת',
  FORBIDDEN: 'אין הרשאה לגשת למשאב זה',
  INVALID_CREDENTIALS: 'דואר אלקטרוני או סיסמה שגויים',
  PENDING_EMAIL_VERIFICATION:
    'חשבונך טרם אומת. אנא לחץ על הקישור שנשלח לתיבת הדואר האלקטרוני שלך (הקישור בתוקף ל-12 שעות).',
  PENDING_ADMIN_APPROVAL:
    'חשבונך אומת בהצלחה וממתין לאישור ההנהלה. עדכון יישלח אליך למייל.',
  LOGIN_SUCCESS: 'ההתחברות בוצעה בהצלחה',
  USER_APPROVED: 'התלמיד אושר בהצלחה',
  USER_REJECTED: 'הבקשה נדחתה והמשתמש נמחק',
  PENDING_USER_NOT_FOUND: 'לא נמצא משתמש הממתין לאישור הנהלה',
  FORGOT_PASSWORD_SUCCESS: 'קישור נשלח למייל',
  INVALID_RESET_TOKEN: 'קישור האיפוס אינו תקין',
  EXPIRED_RESET_TOKEN: 'תוקף קישור האיפוס פג',
  RESET_PASSWORD_SUCCESS: 'הסיסמה עודכנה בהצלחה',
  INVALID_CURRENT_PASSWORD: 'סיסמה שגויה',
  PROFILE_UPDATED: 'הפרטים האישיים עודכנו בהצלחה',
  PASSWORD_CHANGED: 'הסיסמה עודכנה בהצלחה',
  INVALID_PROFILE_IMAGE: 'תמונת הפרופיל אינה תקינה',
  INVALID_ATTENDANCE_DATE: 'תאריך הנוכחות אינו תקין',
  INVALID_ACTIVITY_TYPE: 'סוג הפעילות חייב להיות שיעור או תפילה',
  INVALID_ATTENDANCE_STATUS: 'סטטוס הנוכחות אינו תקין',
  ATTENDANCE_RECORDS_REQUIRED: 'יש לשלוח מערך דיווחי נוכחות',
  ATTENDANCE_SAVED: 'הנוכחות נשמרה בהצלחה',
});

module.exports = {
  ERROR_MESSAGES,
};
